#!/bin/bash
# Koyfin tool-specific messages

echo "koyfin CLI Tools Setup"
echo "======================"
echo ""
echo "======================"
echo "Setup complete!"
echo ""
echo "Binary and session file location:"
echo "  <skills-dir>/koyfin/scripts/"
echo ""
echo "Next step: Authenticate"
echo "  koyfin auth"
echo ""
echo "Usage:"
echo "  koyfin <command> -h"
echo ""
echo "Python utilities:"
echo "  python3 excel_export.py -h"
echo "  koyfin snapshot -kids <list_of_koyfin_ids> | python3 excel_export.py -o snapshot.xlsx"
